"""
Ethan Core package.

Target architecture:
Frontend -> API Routes -> Ethan Core
  -> Context Engine
  -> Memory Engine
  -> Strategy Engine
  -> Runtime Engine
  -> Persistence Engine
  -> Prompt Engine (LLM context only)
  -> Response Engine (data wrapper only)
  -> Output Renderer (only authorized human text source)
  -> Contract Validator (analysis + metadata only before frontend)
  -> OpenAI Gateway

Satellites feed backend data only; they do not call OpenAI and do not decide.
Hard rule: no user-facing Ethan text may leave the backend unless it was
generated by advisor.ethan.output_renderer and validated by contract_validator.
"""
