from product.tiers import (
    ACTIVE_SUBSCRIPTION_STATUSES,
    DISCOVERABLE_MODULES,
    FEATURE_MIN_PLAN,
    PLAN_ALIASES,
    PLAN_ORDER,
    highest_plan,
    is_feature_unlocked,
    normalize_plan,
    plan_allows,
    plan_rank,
    resolve_effective_plan,
    unlocked_features_for_plan,
)
import logging

logger = logging.getLogger(__name__)

PLAN_COPY = {
    "FREE": {
        "name": "Foundation",
        "price": "0 EUR/mois",
        "promise": "Tu construis tes fondations financieres.",
    },
    "GOLD": {
        "name": "Gold",
        "price": "29 EUR/mois",
        "promise": "Je comprends mon patrimoine.",
    },
    "SILVER": {
        "name": "Foundation Plus",
        "price": "legacy",
        "promise": "Tu consolides tes fondations financieres.",
    },
    "PLATINUM": {
        "name": "Advanced Growth",
        "price": "legacy",
        "promise": "Tu acceleres avec des analytics avancees.",
    },
    "ELITE": {
        "name": "Wealth OS",
        "price": "79 EUR/mois",
        "promise": "J'optimise mon patrimoine.",
    },
    "LIBERTY": {
        "name": "Liberty",
        "price": "149 EUR/mois",
        "promise": "Je pilote mon patrimoine.",
    },
    "LEGACY": {
        "name": "Dynasty",
        "price": "399 EUR/mois",
        "promise": "Je construis un patrimoine transmissible.",
    },
}

PLAN_ENTITLEMENTS = {
    "FREE": {
        "max_assets": 10,
        "max_real_estate_assets": 1,
        "real_estate_depth": "simple",
        "max_business_assets": 1,
        "business_depth": "simple",
        "ai_level": "basic",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "basic_score",
            "basic_guidance",
            "wealth_snapshot",
            "future_intelligence_lite",
            "gamification",
        ],
        "features": [
            "simple_wealth_view",
            "income_expense_tracking",
            "wealth_snapshot",
            "next_milestone",
            "future_intelligence_lite",
            "ethan_limited",
            "basic_progression",
            "basic_missions",
            "forex_limited",
        ],
    },
    "GOLD": {
        "max_assets": 20,
        "max_real_estate_assets": 3,
        "real_estate_depth": "cashflow",
        "max_business_assets": 2,
        "business_depth": "structured",
        "pricing_groups": [
            {
                "label": "Comprendre",
                "items": [
                    "20 assets financiers",
                    "3 biens immobiliers avec lecture cashflow",
                    "2 business structures",
                    "Patrimoine visible et activable",
                    "Wealth Map",
                    "Projection 10 ans",
                ],
            },
            {
                "label": "Decider",
                "items": [
                    "Ethan flottant Gold+",
                    "Reconciliation profil par confirmation",
                    "Action utile",
                    "Risque principal",
                    "Opportunite principale",
                    "Scorecard et stress tests simples",
                ],
            },
        ],
        "ai_level": "advanced",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "diversification",
            "real_estate",
            "yield_assets",
            "venture_assets",
            "analytics",
            "command_center",
            "opportunities",
            "advanced_guidance",
            "future_intelligence",
            "wealth_narrative",
            "strategic_intelligence",
            "family_office_intelligence",
            "gamification",
        ],
        "features": [
            "advanced_portfolio",
            "real_estate",
            "business_assets",
            "portfolio_chart",
            "ethan_floating_chat",
            "ethan_profile_reconciliation",
            "weekly_email_insights",
            "smart_notifications",
            "category_opportunities",
            "future_intelligence_full",
            "wealth_narrative",
            "hidden_wealth",
            "opportunity_radar",
            "projections",
            "strategic_intelligence",
            "family_office_scorecard",
            "stress_tests",
            "dependency_detector",
            "forex_full",
        ],
    },
    "SILVER": {
        "max_assets": 10,
        "max_real_estate_assets": 1,
        "real_estate_depth": "simple",
        "max_business_assets": 1,
        "business_depth": "simple",
        "ai_level": "standard",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "basic_score",
            "basic_guidance",
            "gamification",
        ],
        "features": [
            "simple_wealth_view",
            "income_expense_tracking",
            "basic_progression",
            "basic_missions",
            "forex_limited",
        ],
    },
    "PLATINUM": {
        "max_assets": 30,
        "max_real_estate_assets": 3,
        "real_estate_depth": "cashflow",
        "max_business_assets": 2,
        "business_depth": "structured",
        "ai_level": "advanced",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "diversification",
            "real_estate",
            "yield_assets",
            "venture_assets",
            "analytics",
            "command_center",
            "opportunities",
            "advanced_guidance",
            "gamification",
        ],
        "features": [
            "advanced_portfolio",
            "real_estate",
            "business_assets",
            "portfolio_chart",
            "smart_notifications",
            "category_opportunities",
            "projections",
            "forex_full",
        ],
    },
    "ELITE": {
        "max_assets": 30,
        "max_real_estate_assets": 10,
        "real_estate_depth": "simulation",
        "max_business_assets": 5,
        "business_depth": "valuation",
        "pricing_groups": [
            {
                "label": "Optimiser",
                "items": [
                    "30 assets financiers",
                    "10 biens immobiliers avec simulations",
                    "5 business avec valorisation",
                    "Family Office CEO",
                    "Runway",
                    "Lecture operationnelle",
                    "Multi-user",
                    "Companies",
                ],
            },
            {
                "label": "Simuler",
                "items": [
                    "Wealth Narrative enrichi",
                    "Simulations multi-scenarios",
                    "Stress tests avances",
                    "Detecteur de dependances",
                    "Coffre documentaire patrimonial",
                    "Imports assistes",
                    "Graphiques par rubrique",
                    "Allocations avancees",
                ],
            },
        ],
        "ai_level": "premium",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "diversification",
            "real_estate",
            "yield_assets",
            "venture_assets",
            "analytics",
            "command_center",
            "opportunities",
            "advanced_guidance",
            "multi_user",
            "bank_sync",
            "governance",
            "imports",
            "family_office_ceo",
            "strategic_intelligence",
            "family_office_intelligence",
            "gamification",
        ],
        "features": [
            "multi_user",
            "companies",
            "wealth_consolidation",
            "banking_apis",
            "live_sync",
            "premium_guidance",
            "strategic_intelligence",
            "family_office_scorecard",
            "hidden_wealth",
            "stress_tests",
            "dependency_detector",
            "wealth_blocks",
            "multi_scenario_simulations",
            "family_office_intelligence",
            "family_office_ceo",
            "advanced_wealth_narrative",
            "advanced_allocations",
            "governance",
            "automatic_imports",
            "patrimonial_document_inbox",
            "forex_advanced_analytics",
        ],
    },
    "LIBERTY": {
        "max_assets": 50,
        "max_real_estate_assets": None,
        "real_estate_depth": "family_office",
        "max_business_assets": None,
        "business_depth": "family_office",
        "pricing_groups": [
            {
                "label": "Structurer",
                "items": [
                    "50 assets financiers",
                    "Immobilier illimite",
                    "Business illimites",
                    "Family Office Mode complet",
                    "Comptes enfants",
                    "Multi-objectifs",
                    "Scenarios de vie avances",
                    "Probabilites d'atteinte",
                    "Architecture patrimoniale",
                    "Dynasty planning",
                ],
            },
            {
                "label": "Arbitrer",
                "items": [
                    "Family Office Board",
                    "CFO View",
                    "Investor View",
                    "Entrepreneur View",
                    "Family View",
                    "Priorites d'allocation",
                    "Arbitrages strategiques",
                    "Transmission",
                    "Automation",
                    "Sovereign guidance",
                ],
            },
        ],
        "ai_level": "sovereign",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "diversification",
            "real_estate",
            "yield_assets",
            "venture_assets",
            "analytics",
            "command_center",
            "opportunities",
            "advanced_guidance",
            "multi_user",
            "bank_sync",
            "governance",
            "imports",
            "automation",
            "legacy_planning",
            "child_accounts",
            "family_office_mode",
            "family_office_board",
            "gamification",
        ],
        "features": [
            "multi_user",
            "companies",
            "wealth_consolidation",
            "banking_apis",
            "live_sync",
            "sovereign_guidance",
            "advanced_allocations",
            "governance",
            "automatic_imports",
            "wealth_architecture",
            "legacy_planning",
            "child_accounts",
            "family_office_mode",
            "advanced_simulations",
            "advanced_strategic_arbitrage",
            "family_office_board",
            "allocation_priorities",
            "multi_goals",
            "transmission",
            "forex_advanced_analytics",
        ],
    },
    "LEGACY": {
        "max_assets": None,
        "max_real_estate_assets": None,
        "real_estate_depth": "dynasty",
        "max_business_assets": None,
        "business_depth": "dynasty",
        "pricing_groups": [
            {
                "label": "Transmettre",
                "items": [
                    "Assets financiers illimites",
                    "Immobilier et business illimites",
                    "Projection 30 ans",
                    "Transmission familiale",
                    "Family Vault",
                    "Heirs mode",
                    "Protection layer",
                    "Asset protection",
                    "Dynasty governance",
                    "Succession planning",
                    "Global strategy",
                    "Dynasty timeline",
                ],
            },
            {
                "label": "Gouverner",
                "items": [
                    "Gouvernance familiale",
                    "Multi-entites",
                    "Architecture institutionnelle",
                    "Protection et continuite",
                    "Family governance",
                    "Dynasty guidance",
                    "Heirs intelligence",
                    "Global opportunities",
                    "Vault familial",
                    "Scenario successoral",
                    "Continuite familiale",
                    "Patrimoine generationnel",
                ],
            },
        ],
        "ai_level": "dynasty",
        "modules": [
            "foundation",
            "finance",
            "portfolio",
            "diversification",
            "real_estate",
            "yield_assets",
            "venture_assets",
            "analytics",
            "command_center",
            "opportunities",
            "advanced_guidance",
            "multi_user",
            "bank_sync",
            "governance",
            "imports",
            "automation",
            "family_vault",
            "heirs_mode",
            "child_accounts",
            "protection_layer",
            "global_strategy",
            "legacy_timeline",
            "dynasty_governance",
            "gamification",
        ],
        "features": [
            "multi_user",
            "companies",
            "wealth_consolidation",
            "banking_apis",
            "live_sync",
            "dynasty_guidance",
            "advanced_allocations",
            "governance",
            "automatic_imports",
            "wealth_architecture",
            "family_vault",
            "heirs_mode",
            "child_accounts",
            "asset_protection",
            "global_strategy",
            "legacy_timeline",
            "dynasty_governance",
            "succession_planning",
            "family_governance",
            "forex_advanced_analytics",
        ],
    },
}

MODULE_REGISTRY = [
    {
        "key": "foundation",
        "label": "Foundation View",
        "stage": 1,
        "min_plan": "FREE",
        "min_score": 0,
        "description": "Vue claire de ta situation financiere globale.",
    },
    {
        "key": "finance",
        "label": "Revenus / charges",
        "stage": 1,
        "min_plan": "FREE",
        "min_score": 0,
        "description": "Piloter cashflow, epargne et dettes.",
    },
    {
        "key": "portfolio",
        "label": "Portefeuille",
        "stage": 1,
        "min_plan": "FREE",
        "min_score": 0,
        "description": "Centraliser tes premiers actifs financiers.",
    },
    {
        "key": "wealth_snapshot",
        "label": "Wealth Snapshot",
        "stage": 1,
        "min_plan": "FREE",
        "min_score": 0,
        "description": "Voir patrimoine global, repartition et prochain palier.",
    },
    {
        "key": "future_intelligence_lite",
        "label": "Future Intelligence Lite",
        "stage": 1,
        "min_plan": "FREE",
        "min_score": 0,
        "description": "Lire une premiere trajectoire patrimoniale sans profondeur avancee.",
    },
    {
        "key": "diversification",
        "label": "Exposition",
        "stage": 2,
        "min_plan": "GOLD",
        "min_score": 35,
        "description": "Voir les concentrations et arbitrages prioritaires.",
    },
    {
        "key": "forex",
        "label": "Forex / Currencies",
        "stage": 2,
        "min_plan": "FREE",
        "min_score": 0,
        "description": "Suivre une exposition simple aux devises sans interface de trading.",
    },
    {
        "key": "real_estate",
        "label": "Immobilier",
        "stage": 3,
        "min_plan": "GOLD",
        "min_score": 45,
        "description": "Piloter biens, rendement et plus-value potentielle.",
    },
    {
        "key": "yield_assets",
        "label": "Prets & Private Equity",
        "stage": 3,
        "min_plan": "GOLD",
        "min_score": 45,
        "description": "Suivre capital prete, rendement et valeur finale.",
    },
    {
        "key": "venture_assets",
        "label": "Business Cockpit",
        "stage": 4,
        "min_plan": "GOLD",
        "min_score": 55,
        "description": "Analyser business, startup, franchise et activites digitales.",
    },
    {
        "key": "command_center",
        "label": "Command Center",
        "stage": 5,
        "min_plan": "GOLD",
        "min_score": 60,
        "description": "Prioriser risques, opportunites et prochaines actions.",
    },
    {
        "key": "opportunities",
        "label": "Opportunites",
        "stage": 5,
        "min_plan": "GOLD",
        "min_score": 50,
        "description": "Recevoir des signaux personnalises par rubrique patrimoniale.",
    },
    {
        "key": "advanced_guidance",
        "label": "Guidance avancee",
        "stage": 5,
        "min_plan": "GOLD",
        "min_score": 50,
        "description": "Transformer ton contexte en actions prioritaires.",
    },
    {
        "key": "future_intelligence",
        "label": "Future Intelligence",
        "stage": 5,
        "min_plan": "GOLD",
        "min_score": 0,
        "description": "Regrouper Wealth Map, timeline, simulations et film du futur.",
    },
    {
        "key": "wealth_narrative",
        "label": "Wealth Narrative",
        "stage": 5,
        "min_plan": "GOLD",
        "min_score": 0,
        "description": "Transformer les donnees patrimoniales en lecture narrative backend.",
    },
    {
        "key": "strategic_intelligence",
        "label": "Strategic Intelligence",
        "stage": 6,
        "min_plan": "GOLD",
        "min_score": 0,
        "description": "Regrouper risque, opportunite, decision et levier principal dans une lecture simple.",
    },
    {
        "key": "family_office_intelligence",
        "label": "Family Office Intelligence",
        "stage": 6,
        "min_plan": "GOLD",
        "min_score": 0,
        "description": "Scorecard, stress tests simples et dependances consolidees.",
    },
    {
        "key": "family_office_ceo",
        "label": "Family Office CEO",
        "stage": 6,
        "min_plan": "ELITE",
        "min_score": 0,
        "description": "Burn rate, marge mensuelle, runway et lecture operationnelle du patrimoine.",
    },
    {
        "key": "family_office_board",
        "label": "Family Office Board",
        "stage": 8,
        "min_plan": "LIBERTY",
        "min_score": 0,
        "description": "Analyser la trajectoire sous les angles CFO, investisseur, entrepreneur et famille.",
    },
    {
        "key": "multi_user",
        "label": "Multi-user",
        "stage": 6,
        "min_plan": "ELITE",
        "min_score": 70,
        "description": "Partager le pilotage patrimonial avec ton equipe/famille.",
    },
    {
        "key": "bank_sync",
        "label": "Synchronisation live",
        "stage": 7,
        "min_plan": "ELITE",
        "min_score": 80,
        "description": "Architecture preparee pour connexions bancaires et imports.",
    },
    {
        "key": "legacy_planning",
        "label": "Dynasty planning",
        "stage": 8,
        "min_plan": "LIBERTY",
        "min_score": 85,
        "description": "Gouvernance avancee, transmission et architecture patrimoniale.",
    },
    {
        "key": "child_accounts",
        "label": "Comptes enfants",
        "stage": 8,
        "min_plan": "LIBERTY",
        "min_score": 0,
        "description": "Portefeuille enfant, objectifs education et score generationnel.",
    },
    {
        "key": "family_vault",
        "label": "Family Vault",
        "stage": 9,
        "min_plan": "LEGACY",
        "min_score": 0,
        "description": "Coffre-fort familial, documents, succession et notes privees.",
    },
    {
        "key": "heirs_mode",
        "label": "Heirs Mode",
        "stage": 9,
        "min_plan": "LEGACY",
        "min_score": 0,
        "description": "Preparation des heritiers, education financiere et module junior.",
    },
    {
        "key": "protection_layer",
        "label": "Protection Layer",
        "stage": 9,
        "min_plan": "LEGACY",
        "min_score": 0,
        "description": "Vulnerabilite, concentration, inflation lifestyle et protection patrimoniale.",
    },
    {
        "key": "global_strategy",
        "label": "Global Strategy",
        "stage": 9,
        "min_plan": "LEGACY",
        "min_score": 0,
        "description": "Diversification geographique, residence fiscale et strategie internationale.",
    },
    {
        "key": "legacy_timeline",
        "label": "Dynasty timeline",
        "stage": 9,
        "min_plan": "LEGACY",
        "min_score": 0,
        "description": "Projection 10 ans, 20 ans et vision generationnelle.",
    },
]


def inherited_values(plan: str, field: str):
    normalized = normalize_plan(plan)
    values = []

    for candidate, entitlements in PLAN_ENTITLEMENTS.items():
        if plan_allows(normalized, candidate):
            for value in entitlements.get(field, []):
                if value not in values:
                    values.append(value)

    return values


def build_entitlements(plan: str):
    normalized = normalize_plan(plan)
    base = dict(PLAN_ENTITLEMENTS[normalized])
    base["modules"] = inherited_values(normalized, "modules")
    base["features"] = sorted(set([
        *inherited_values(normalized, "features"),
        *unlocked_features_for_plan(normalized),
    ]))

    return {
        "plan": normalized,
        "copy": PLAN_COPY[normalized],
        **base,
    }


def can_access_module(plan: str, score: int, module: dict) -> bool:
    normalized = normalize_plan(plan)
    required = normalize_plan(module["min_plan"])

    return plan_allows(normalized, required) and score >= int(module.get("min_score", 0))


def is_feature_enabled(user_plan: str, feature_key: str) -> bool:
    enabled = is_feature_unlocked(user_plan, feature_key)
    logger.info(
        "feature_unlock_check plan=%s feature=%s enabled=%s",
        normalize_plan(user_plan),
        feature_key,
        enabled,
    )
    return enabled

